url: "https://whycoffee.blog" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "why coffee?" # the name of your site, e.g. ACME Corp.
description: "Still trying to write something about coffee."
lang: "zh-Hant-TW"
permalink: /:categories/:year/:month/:day/:title

exclude:
- vendor
- about.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "tag/*.md"
    values:
      sitemap: false
  -
    scope:
      path: "about_text.md"
    values:
      sitemap: false

algolia:
  application_id: M50XXOEO0I
  index_name:     whycoffee # You can replace that with whatever name you want
  search_only_api_key: ad302026cfd538a86592ae475eca5437
  extensions_to_index:
    - html
    - md
  files_to_exclude:
    - ./*.md
    - ./tag/*.md
  settings: 
    searchableAttributes:                                                        
      - title
      - maintitle                                                               
      - subtitle                                              
      - headings                                                                 
      - unordered(content)                                                       
      - unordered(tags)  
    attributesToHighlight:                                                       
      - categories                                                               
      - content                                                                  
      - headings                                                                 
      - html                                                                     
      - subtitle
      - maintitle                                                                 
      - tags                                                                     
      - title
