url: "https://whycoffee.blog/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "why coffee?" # the name of your site, e.g. ACME Corp.
description: "Still trying to write something about coffee."

include:
- _pages

defaults:
  - 
    scope:
      path: '_pages'
    values:
      permalink: /:basename/

exclude:
- vendor
- about.md

algolia:
  application_id: M50XXOEO0I
  index_name:     whycoffee # You can replace that with whatever name you want
  search_only_api_key: ad302026cfd538a86592ae475eca5437
  extensions_to_index:
    - html
    - md
  files_to_exclude:
    - ./_pages/*.md
    - ./tag/*.md
    - ./index.md
    - ./about_text.md
  settings: 
    searchableAttributes:                                                        
      - title                                                               
      - subtitle                                              
      - headings                                                                 
      - unordered(content)                                                       
      - collection,categories,tags     
    attributesToHighlight:                                                       
      - categories                                                               
      - collection                                                               
      - content                                                                  
      - headings                                                                 
      - html                                                                     
      - subtitle                                                                 
      - tags                                                                     
      - title
