url: "https://timothyweng.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "why coffee?" # the name of your site, e.g. ACME Corp.
description: "Still trying to write something about coffee."

exclude: [vendor]

algolia:
  application_id: M50XXOEO0I
  index_name:     whycoffee # You can replace that with whatever name you want
  search_only_api_key: ad302026cfd538a86592ae475eca5437
  extensions_to_index:
    - html
    - md
  files_to_exclude:
    - search.md
    - gallery.md
    - articles.md
    - contact.md
    - about.md
    - index.md
    - ./tag/*.md      

