menu:
# - {name: 'people', url: '/people'}
# - {name: 'publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
# - {name: 'cv', url: '/cv'}
- {name: 'home', url: '/'}
- {name: 'about', url: '/about'}
- {name: 'articles', url: '/articles'}
- {name: 'gallery', url: '/gallery'}
- {name: 'contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

galleryleft:
- {location: '蘭嶼', year: '2020', url: 'lanyu.jpg'}
- {location: '蘭嶼', year: '2020', url: 'island.jpg'}
- {location: '奧日光', year: '2019', url: 'nikko.jpg'}
- {location: '日暮里車站', year: '2019', url: 'trainstation.jpg'}
- {location: '池袋', year: '2019', url: 'dawn.jpg'}

galleryright:
- {location: '桃園', year: '2020', url: 'sunset.jpg'}
- {location: '台灣大學', year: '2020', url: 'house.jpg'}
- {location: '台灣大學', year: '2019', url: 'door.jpg'}
- {location: '湘南海岸', year: '2019', url: 'surf.jpg'}
- {location: '湘南海岸', year: '2019', url: 'coast.jpg'}


# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
# - {icon: 'github', link: 'https://github.com/LeNPaul'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'fab fa-instagram', link: 'https://instagram.com/why.309'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'fab fa-facebook', link: 'https://www.facebook.com/haoyong0309'}
# - {icon: 'far fa-envelope', link: 'mailto: tim0309.tw@gmail.com'}

contacts:
- {name: '翁浩永', title: '23rd 社長', department: '台大咖啡社', institution: '資訊工程系', institution_address: '台灣大學', phone: '(000) 000-0000', email: 'tim0309.tw@gmail.com', office: 'Science Building 505', image: 'assets/img/about.JPG'}
